name: Ping it in every 5 minutes

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/4 * * * *"

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Don't let him die bro
        run: |
          curl -X GET ${{ secrets.LOAD_REPO_URL }}
          
